### ISSUE TITLE
Replacing `&nbsp;` to `\n` by SaxLtx parser

### ISSUE THREAD

**Issue by dimatill** [node-xmpp/ltx#76]
I have left the comment here https://github.com/node-xmpp/ltx/commit/bb8980eed61a479397084883c483a4a613615679

**Comment by sonnyp** [comment]
@lloydwatkin any idea?

**Comment by sonnyp** [comment]
https://github.com/node-xmpp/ltx/pull/79

**Comment by sonnyp** [comment]
fixed in https://github.com/node-xmpp/ltx/pull/79

**Comment by dimatill** [comment]
@sonnyp I still have a problem in lib/parsers/ltx.js. Please check https://github.com/node-xmpp/ltx/blob/master/lib/parsers/ltx.js#L171

**Comment by sonnyp** [comment]
https://github.com/node-xmpp/ltx/pull/84

**Comment by sonnyp** [comment]
fixed, released as version 2.2.1

**Comment by dimatill** [comment]
Thank you!
